language: rust
rust:
  - nightly
install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-arm-embedded -y
script:
  - cargo test
  - cargo build --release --target thumbv7em-none-eabi
  - cargo doc
