language: rust
rust:
  - nightly
install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-arm-embedded -y
  - rustup target add thumbv7em-none-eabi
  - rustup component add rustfmt
script:
  - cargo test --all
  - cargo build --release --target thumbv7em-none-eabi
  # rustdoc fails with associated types:
  # https://github.com/rust-lang/rust/issues/58011
  #
  # - cargo doc --target thumbv7em-none-eabi
  - cargo fmt -- --check
