#!/usr/bin/env expect

# exp_internal 1

if {$argc != 1} {
    puts "usage: test.exp port"
    exit
}

set port $argv
set spawned [spawn -open [open $port w+]]
set baud 9600

stty ispeed $baud ospeed $baud raw -echo cs8 -parenb -cstopb onlcr < $port

proc reset {} {
    system "openocd -f openocd.cfg -c 'reset; exit' 2> /dev/null"
}

proc expect_exact {pattern} {
    expect {
        default {
            error "\n\nTimed out waiting for \"$pattern\"\n";
            exit 1;
        }
        "^$pattern"
    }
}

proc expect_prompt {} {
    expect_exact "> "
}

proc send_command {cmd} {
    send -- "$cmd\r"
    expect "\n"
}

# test welcome prompt
reset
expect_exact "*Welcome to bkernel!\r\n"
expect_exact "Type 'help' to get a list of available commands.\r\n"
expect_prompt

# test hi
send_command "hi"
expect_exact "Hi, there!\r\n"
expect_prompt

# test LED commands
send_command "-3"
expect_prompt
send_command "-4"
expect_prompt
send_command "-5"
expect_prompt
send_command "-6"
expect_prompt

send_command "+3"
expect_prompt
send_command "+4"
expect_prompt
send_command "+5"
expect_prompt
send_command "+6"
expect_prompt

# test unknown command
send_command "+7"
expect_exact "Unknown command: \"+7\"\r\n"
expect_prompt

send_user "\n\nTests successful\n"
