[package]
name = "breactor"
version = "0.0.1"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.1", default-features = false }
stm32f4 = { path = "../stm32f4" }