[package]
name = "breactor"
version = "0.0.1"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]
edition = "2018"

[dependencies]
futures = { package = "futures-preview", version = "0.3.0-alpha.16", default-features = false }
stm32f4 = { path = "../stm32f4" }