[package]
name = "bscheduler"
version = "0.0.1"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]
build = "../build.rs"

[lib]
name = "bscheduler"
path = "lib.rs"

[target.'cfg(not(target_os = "none"))'.dependencies]
lazy_static = "0.1.*"