[package]
name = "smalloc"
version = "0.0.1"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]
edition = "2018"

[lib]
name = "smalloc"
path = "lib.rs"

[dev-dependencies]
rand_isaac = "0.1.1"
rand = "0.6.5"